#!/bin/bash
RELEASE=$1

mkdir -p usr/{bin/,lib/python2.5/site-packages/aarddict/locale,share/{applications/hildon/,dbus-1/services/,pixmaps}}

cp ../run usr/bin/aarddict || exit

for i in "*.py" "*.js" "*.png" "*.cfg" "*.css" "*.tmpl" locale icons
do
  cp -R ../aarddict/$i usr/lib/python2.5/site-packages/aarddict || exit
done

cp -R ../icons/ usr/share/
chmod +x usr/bin/aarddict

DIRS="usr"
rm $(find $DIRS -name "*~")
rm $(find $DIRS -name "*.po")
rm $(find $DIRS -name "*.pot")
rm $(find $DIRS -name "*.ts")

PACKAGE=aarddict
VERSION=`python -c "import aarddict; print aarddict.__version__"`
APP_NAME=`python -c "import aarddict; print aarddict.__appname__"`
SIZE=$(du -sc $DIRS|grep total|sed s/total//)

echo $VERSION	

echo "Package: $PACKAGE
Version: $VERSION
Section: user/other
Priority: optional
Architecture: all
Depends: python2.5, python2.5-qt4-core (>= 4.6.2), python2.5-qt4-gui (>= 4.6.2), python2.5-qt4-network (>= 4.6.2), python2.5-qt4-webkit (>= 4.6.2), pyicu (>= 0.8.1), python-simplejson
Replaces: simplejson
Conflicts: simplejson
Installed-Size: $SIZE
Suggests: ttf-sil-doulos
Maintainer: Igor Tkach <itkach@aarddict.org>
Homepage: http://aarddict.org
Description: Aard Dictionary is a dictionary and offline Wikipedia reader 
 Aard Dictionary is a free, fast, easy to use word lookup program that
  * looks up words fast even with huge dictionaries like 
    English Wikipedia
  * looks up words in multiple dictionaries in multiple 
    languages without switching
  * works great as offline Wikipedia reader
  * is keyboard navigation friendly
  * has efficient, highly compressed dictionary data storage 
    format with ability to verify data integrity built-in 
 .
 Download Wikipedia and dictionaries at http://aarddict.org or 
 compile your own dictionaries with Aard Tools.
Maemo-Icon-26:
 iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABGdBTUEAAK/I
 NwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAfw
 SURBVHjajFZ5bBTnFf/NzM6es/fh9dpeXxTHJ8E4hCtRiQK0SZr+EVWoJD0S
 qYmiRiQoUaWqTSo1UquqURsiUGh6kDZKI3qEOiIgGgKUwwgMAQMuxYDP9Xrt
 9V7e3Zndnatvh6NOhdR+0uw3s/PN+733e7/3vo/BovHw0y8BDGPcM5oOnWPB
 qBp0ll20Sq++vXN//INdwa6e5d8Z+uzMm+uffEG8veqT3283Zp7nIVcqWGzh
 /x6fvvumJzF0/HFvJfPxj9/YMfLE17+xVVHUss4yuH1VAfxeLxrq64xvTHe+
 Zpi7Gj303lvm2rpojdcfiLo93oeamls2/WT7r3qC4YjTYrHCYjYhdmNkHLpu
 sHAnbl27Gfstu6ZFb5C6ev5bNXUN6ywWi4Ne17oFT3jbqz8NBUI1DsHpor8t
 sPAmWKuzmadvNJDzCAaDAY8/ENEZZuq2OUVWPuew6XY0nWY/os0tX2vvXfOo
 4LDBTKFXr6pBi9ls3ENXiWsdVnMVjEcuk4HdasbStjah9957nyPUH94hiPKq
 6/+JkKv+rNv4mP+evo693R3tDYIvFHIJAngTSwZ5MOS1jYw5BQc0pQKe42Ai
 Iz6P1wCr6qQK1tHe3vnW6z/YX9+xfK7KmZxKwMzxCK7ow3ef2sIYYgjWNz/T
 trR5w/de3tYlmFkybIHNYgbH6EQVRzPgsFkRCvhhMXF0sQQIBHwe2MiZsiSh
 t6/P/8s3ftE/sOed7qpNqSRBJScVDShWZN7Us3JNkDfpTyXzo2zVvaDTigrl
 wWETUCmXYCKJa6oClmjzuj2wEkjVcKmYR9DfRAJQUVjIITkzg81btrREIuFj
 r7zy8vORUEB9aP36p8O1tZH33n//WVO06/4v53OjPQ1LW3Hs6FF8oakBV8an
 IQR8UHnWqBUGFiiVkpEvwe7H/NycQWk+l0ZtpA7ztGwhl0UuncSGjZs8x0+s
 +sDr9UBVFJw8fgKHDh95jpUZa6c77MLlpIC3//i3m4rJp4lftqomQ2V2opKn
 53w2DZvNhvq6CDh6LokFiLkMWpa0oqWpCWECnRwfoxzelHQ6lUYsFkOorrGP
 VZTyOp64DkYFZD0CTg8Owm63IXZtmEB4hAisqjSnww5VrqAiFiE4nWhqbCTB
 mJBOp5CdT8JH67LpNPILC3B7fUY04xMTGB6+gG8+84SFJfabxrMmLI2mkCqz
 +PDIPyAWi0jEpxGfuAHBISDg9xn1IjgcWKCo1LIEn8+LlpYWuN1uCILTiGBg
 YICiihj3sakY/vKnPXj04VZw84MuE4nCPpsTkEnx6F0ZwNBFN46dOo36UBBn
 Tp0kmupQW1+PNCFJRBVPapybJelSvpwutxFddRw9fBgOux2UfKO+3tm1C4I1
 h0L8LK6lNAsLpaSwLId/TtiQL0iktDLOiyymE7MYHxvD3j/vMaiJNjXC43IZ
 Fa9Rq0nOJWlWDZDpqUlMTU2hqbkZ10ZG8KPXXsPUxEU80KVh4OokxqCoJp5l
 5vVKMZAveWGv6Pjqg3ZEvDU4eiBO8S/gxMmTyGSz2Prii2igvOiYhCiJqAmH
 UXWwkF/A7t3v4ty5s9i5cyfcHhfsDuCRrzTht2dM0E1u+HRO5JY9+KVV06nZ
 HovNjERSxOMdbqzpYbHsPhfcQiMuXRjFpUsXcfHCEBqjUdzT0QEv5afaUIuF
 Al7auhX9+/ZBYqn+GrqghAJoa6vFkQs6TkxXYLVL8PCe61zXyrWtY9PxjSq1
 lvVtUay+X4cMCRNUF0uWuNC1shWTYwVcv3od/f0fwUpKXE5tpTre3rEDez7c
 C1vfBmjhFqisCYWijMvxMpIZCaxUhNMGOE2u/Vx7V1exXNY2zxZEW2dQQU1H
 CumKjLDDC7FCgNkbWL0xBD7UicmJIo4e+jsO7t9PfU/Gzl//TrOsfozhbA6U
 KTqOnOWoAbNyGVq1xojiiMemcwrzc+7K+bOzy3rv6xmbS3fbNA09K72YLM+h
 ot5s85xmRqyQBu+X0N27AvZQG66MjOHwuWFqklGmQhtAaSFvbDOMAcRDJQfF
 XA5Kbha9zTWnPvlr/+tG917Wu3y0kExtHpnN2CJ2Ac5GCTOlCsq6goqpDIVW
 aSYZDlcaX+y1YtuT6xCJtmFwUoaYF6FKZRIGCxNJH1AhZagmEzG4tbLaEAq/
 en7wzGkD6MrQ+cTqtWvVKxNTGzPTIjZ0LIPuyCIrl6CRgUK+gHyxhNKchLCo
 orvehrl5GR+fnKbzgAxNlqBRQVe3DFkqoJCcobUJhP2+3ccO7vsZQWjc7Y3p
 2vDFwVW9K0JD8UTf0MAYNrX3oIIcGEWFIpIxkeonVYaQVcgBM77/mzGk87QR
 UrOVqVPwZg6qRgxQo12ITYCRCgcLqZlnK6WSeGfjuzW02Oi1T1saGgJjqVxf
 kKH9R1Jw+rMJ+OoEaAUF6dEFpHIFXI5ZcWmagYmKWy2LBpBK0TMEJCYTkJPx
 A1qp+G2psJD63A67aCiZ2fgBplxKyjrX/UBnqzsTj8NLm106mcco5WR40op/
 jZPBbAFyqUCdpEjUlelLijw7lxVnpraXcqnnVUXOLTbM3eXgo5N7Z+aTyf7x
 mYwadbncXqc5WIzruHCd+kJCQjlDKmSIJgJSqDPoYmFczs9/VErNvlDOZ/9Q
 dfi/jTL/6wxntVrctbXBRxKS2qWIpSDLsC7jHEVZox9qeOqoJlf65XJp9tbp
 8q7j3wIMABV0lBSSGIi6AAAAAElFTkSuQmCC
 ====
 " > control
cat control

echo "[Desktop Entry]
Encoding=UTF-8
Name=$APP_NAME
Type=Application
Exec=/usr/bin/aarddict
Icon=aarddict
X-HildonDesk-ShowInToolbar=true
X-Osso-Type=application/x-executable" > usr/share/applications/hildon/aarddict.desktop

echo "[D-BUS Service]
Name=com.nokia.aarddict
Exec=/usr/bin/aarddict" > usr/share/dbus-1/services/aarddict.service

echo 2.0 > debian-binary

tar -zcvf data.tar.gz ./usr 
tar -zcvf control.tar.gz control postinst
NAME=${PACKAGE}_${VERSION}-${RELEASE}maemo_armel.deb
rm $NAME
ar q $NAME debian-binary control.tar.gz data.tar.gz 
ar t $NAME
ls -al $NAME
rm debian-binary control control.tar.gz data.tar.gz
rm -rfd usr
