#!/bin/sh
mkdir -p usr/bin
mkdir -p usr/share/applications/hildon/
mkdir -p usr/share/dbus-1/services/
mkdir -p usr/share/pixmaps
cp ../src/*.py usr/bin || exit
cp ../icons/sdictviewer.png usr/share/pixmaps/

chmod +x usr/bin/sdictview-maemo.py

export LD_LIBRARY_PATH=/usr/lib

DIRS="usr"
find $DIRS| grep \~ && rm -i $(find $DIRS| grep \~)

PACKAGE=sdictviewer
VERSION=$(grep "^version =" ../src/pysdic.py | sed s/version\ =\ \"// | sed s/\"//)
SIZE=$(du -sc $DIRS|grep total|sed s/total//)

echo $VERSION	

echo "Package: $PACKAGE
Version: $VERSION
Section: user/other
Priority: optional
Architecture: all
Depends: $DEPENDS
Installed-Size: $SIZE
Maintainer: Igor Tkach <itkach@users.sourceforge.net>
Description: A dictionary application that works with dictionaries from http://sdict.com" > control
cat control

echo "[Desktop Entry]
Version=$VERSION
Encoding=UTF-8
Name=SDict Viewer
Type=Application
Exec=/usr/bin/sdictview-maemo.py
Icon=sdictviewer
X-Osso-Service=sdictviewer
X-Osso-Type=application/x-executable" > usr/share/applications/hildon/sdictviewer.desktop

echo "[D-BUS Service]
Name=com.nokia.sdictviewer
Exec=/usr/bin/sdictview-maemo.py" > usr/share/dbus-1/services/sdictviewer.service

echo 2.0 > debian-binary

tar -zcvf data.tar.gz ./usr 
tar -zcvf control.tar.gz control
NAME="$PACKAGE"-"$VERSION"-py"$PYVERSION".deb
rm $NAME
ar q $NAME debian-binary control.tar.gz data.tar.gz 
ar t $NAME
ls -al $NAME
rm debian-binary control control.tar.gz data.tar.gz
rm -rfd usr
